[general]
GOOGLE_API_KEY = "AIzaSyA8BIDH4fJTmUkZ4sgVgZtEntTCh04h8ug"
SANITY_API_TOKEN = "skaHcQbhBIADeOUy6uYClqu645uFjsH8N7pfBnX9xa2fHMBmeDEue3xdY2ECEJ8M7mBDruO3LAwJIMHoohq0elhs35OzM5iFEFRjsTvHVF5EiFN2aerIoAIVkkPAYLctEuG7qE6NzSsw8hsEvodBx6qybuVfOSYilLxkistaGmqwQcoT4LRf"